import { PropListType } from "../../types/AfterSchoolType";

export const list: PropListType[] = [
  {
    id: 1,
    title: "컴활",
    week: ["MON", "MON"],
    grade: 1,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 2,
    title: "배드민턴",
    week: ["MON"],
    grade: 1,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 3,
    title: "축구",
    week: ["MON"],
    grade: 2,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 4,
    title: "컴퓨터활용능력",
    week: ["MON", "WED"],
    grade: 2,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 5,
    title: "게임개발",
    week: ["MON", "TUE"],
    grade: 3,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 18,
    title: "치킨",
    week: ["MON"],
    grade: 3,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 6,
    title: "컴활",
    week: ["TUE"],
    grade: 1,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 7,
    title: "컴퓨터활용능력",
    week: ["TUE"],
    grade: 1,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 8,
    title: "수학",
    week: ["TUE"],
    grade: 2,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 9,
    title: "치킨먹고싶다",
    week: ["TUE"],
    grade: 2,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 10,
    title: "슈슉슈슉",
    week: ["TUE"],
    grade: 3,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 11,
    title: "슈발럼아",
    week: ["TUE"],
    grade: 3,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 12,
    title: "전승원멍청이",
    week: ["WED"],
    grade: 1,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 13,
    title: "나도",
    week: ["WED"],
    grade: 1,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 14,
    title: "ㅎㅎㅎㅎ",
    week: ["WED"],
    grade: 2,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 15,
    title: "오늘뭐하지",
    week: ["WED"],
    grade: 2,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 16,
    title: "내일뭐하지",
    week: ["WED"],
    grade: 3,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 17,
    title: "치킨먹을까",
    week: ["WED"],
    grade: 1,
    personnel: 13,
    maxPersonnel: 25,
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
];
