import { PropListType } from "../../types/AfterSchoolType";

export const list: PropListType[] = [
  {
    id: 1,
    title: "컴활",
    week: ["MON"],
    grade: 1,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
  {
    id: 2,
    title: "배드민턴",
    week: ["MON"],
    grade: 1,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
  {
    id: 3,
    title: "축구",
    week: ["MON"],
    grade: 2,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
  {
    id: 4,
    title: "컴퓨터활용능력",
    week: ["MON", "WED"],
    grade: 2,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
  {
    id: 5,
    title: "게임개발",
    week: ["MON", "TUE"],
    grade: 3,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
  {
    id: 6,
    title: "치킨",
    week: ["MON"],
    grade: 3,
    teacher: "",
    season: "FIRST",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 7,
    title: "컴활",
    week: ["TUE"],
    grade: 1,
    teacher: "",
    season: "FIRST",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
  },
  {
    id: 8,
    title: "컴퓨터활용능력",
    week: ["TUE"],
    grade: 1,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
  {
    id: 9,
    title: "수학",
    week: ["TUE"],
    grade: 2,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
  {
    id: 10,
    title: "치킨먹고싶다",
    week: ["TUE"],
    grade: 2,
    teacher: "",
    isOpend: true,
    isApplied: false,
    isEnabled: true,
    season: "FIRST",
  },
];
